name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          IT_API_KEY: ${{ secrets.IT_API_KEY }}
          IT_STEAM_ID: ${{ secrets.IT_STEAM_ID }}
        run: cargo test --verbose
